### ISSUE TITLE
Is the MIT license ok for this?

### ISSUE THREAD

**Issue by shishkin** [SingaporeScalaProgrammers/scala-workshop#1]
Please comment or vote with reactions.

**Comment by hhandoko** [comment]
For the code, I think MIT or Apache 2 is fine... For the materials, how about a Creative Commons one (e.g. CC by-SA).

**Comment by shishkin** [comment]
Alright, CC-BY and MIT it is, since it is better aligned with MIT (no share-alike requirement). It's not set in stone though before we get real content. So please raise your concerns before contributing if you feel like it.
